mod 'puppetlabs-stdlib', '8.5.0'
mod 'puppetlabs-apt', '9.0.2'
mod 'puppet-kibana', '7.0.1'
mod 'puppet-elastic_stack', '8.0.2'
mod 'puppet-yum', '6.2.0'
mod 'puppetlabs-concat', '7.3.3'
mod 'puppetlabs-java', '9.0.1'
mod 'puppet-logstash', '7.0.0'
mod 'puppet-elk',
  :git => 'https://github.com/hepexta/puppet-elk.git'
