# -*- mode: ruby -*-
# vi: set ft=ruby :
# 	elk.vm.provision "shell", inline: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
#	elk.vm.provision "shell", inline: "systemctl restart sshd.service"
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

PUPPETLABS_APT_SETUP = <<-EOF
wget https://apt.puppetlabs.com/puppet5-release-xenial.deb
sudo dpkg -i puppet5-release-xenial.deb
sudo apt update
EOF

Vagrant.configure("2") do |config|
  config.vm.define "elk" do |elk|
    elk.vm.provider "virtualbox" do |v2|
	  v2.name = "elk.vm"
      v2.cpus = 2
      v2.memory = 2048
    end
    elk.vm.network "forwarded_port", guest: 5601, host: 5601
    elk.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"#, ip: "192.168.50.20"
    elk.vm.hostname = "elk.local"
    elk.vm.box = "bento/ubuntu-22.10"
    elk.vm.provision "shell", inline: PUPPETLABS_APT_SETUP
    elk.vm.provision "shell", inline: "sudo apt-get install -y puppet-agent vim"
    elk.vm.provision "shell", inline: %q(puppet apply -e "host {'puppet.local': ip => '192.168.50.10', host_aliases => ['puppet']}")
	elk.vm.provision "shell" do |s|
		ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
		s.inline = <<-SHELL
		  echo #{ssh_pub_key} >> /home/elk/.ssh/authorized_keys
		  echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
		SHELL
	end
  end
  config.ssh.insert_key = true
end

